### ISSUE TITLE
env: node: No such file or directory on compile and display JS

### ISSUE THREAD

**Issue by rebelwarrior** [textmate/coffee-script.tmbundle#9]
No sure what's causing this. TM_COFFEE seems to be set correctly.

**Comment by rebelwarrior** [comment]
Found the problem even with TM_COFFEE and TM_NODE set correctly if the PATH is doesn't include the node and coffee paths, the coffee tmbundle 'Run' command will not work. I"m not sure what is causing this but the error should be caught and expanded on with a suggestion to fix the path.

**Comment by infininight** [comment]
Fixed by improving `requiredCommands`, should now work automatically when node is installed through MacPorts or Homebrew. Thanks for the report.
